snapshot1 = load('snapshot1.mat');
snapshot2 = load('snapshot2.mat');
snapshot3 = load('snapshot3.mat');
snapshot4 = load('snapshot4.mat');
snapshot5 = load('snapshot5.mat');
snapshot6 = load('snapshot6.mat');
snapshot7 = load('snapshot7.mat');
snapshot8 = load('snapshot8.mat');
snapshot9 = load('snapshot9.mat');
snapshot10 = load('snapshot10.mat');
snapshot11 = load('snapshot11.mat');
snapshot12 = load('snapshot12.mat');
snapshot13 = load('snapshot13.mat');
snapshot14 = load('snapshot14.mat');
snapshot15 = load('snapshot15.mat');
snapshot16 = load('snapshot16.mat');
snapshot17 = load('snapshot17.mat');
snapshot18 = load('snapshot18.mat');
snapshot19 = load('snapshot19.mat');
snapshot20 = load('snapshot20.mat');
snapshot21 = load('snapshot21.mat');
snapshot22 = load('snapshot22.mat');
snapshot23 = load('snapshot23.mat');

cwi_data = cat(3, snapshot1.snapshot,...
                  snapshot2.snapshot,...
                  snapshot3.snapshot,...
                  snapshot4.snapshot,...
                  snapshot5.snapshot,...
                  snapshot6.snapshot,...
                  snapshot7.snapshot,...
                  snapshot8.snapshot,...
                  snapshot9.snapshot,...
                  snapshot10.snapshot,...
                  snapshot11.snapshot,...
                  snapshot12.snapshot,...
                  snapshot13.snapshot,...
                  snapshot14.snapshot,...
                  snapshot15.snapshot,...
                  snapshot16.snapshot,...
                  snapshot17.snapshot,...
                  snapshot18.snapshot,...
                  snapshot19.snapshot,...
                  snapshot20.snapshot,...
                  snapshot21.snapshot,...
                  snapshot22.snapshot,...
                  snapshot23.snapshot);

save('cwi_data_concatenated.mat', "cwi_data");

