function [s,s_udg] = source2d(p,udg,param,time)
%SOURCE2D
%    [S,S_UDG] = SOURCE2D(P,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Aug-2023 14:09:57
[ng,nc] = size(udg);
nch = 1;
nd = 2;
one = ones(ng,1);
param4 = param{4};
param5 = param{5};
u1 = udg(:,1);
x1 = p(:,1);
zero = zeros(ng,1);
s = param4.*param5.*u1.*x1;
if nargout > 1
    s_udg = [one.*param4.*param5.*x1;zero;zero];
end
s = reshape(s,ng,nch);
s_udg = reshape(s_udg,ng,nch,nc);
end