function [f,f_udg] = flux2d(p,udg,param,time)
%FLUX2D
%    [F,F_UDG] = FLUX2D(P,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Aug-2023 14:02:35
[ng,nc] = size(udg);
nch = 1;
nd = 2;
one = ones(ng,1);
param1 = param{1};
param2 = param{2};
param5 = param{5};
u1 = udg(:,1);
u2 = udg(:,2);
u3 = udg(:,3);
x1 = p(:,1);
zero = zeros(ng,1);
t2 = 1.0./param2;
t3 = 1.0./param5;
f = [param1.*t2.*t3.*u2.*x1;x1.*(u1+param1.*t2.*t3.*u3)];
if nargout > 1
    t4 = one.*param1.*t2.*t3.*x1;
    f_udg = [zero;one.*x1;t4;zero;zero;t4];
end
f = reshape(f,ng,nch,nd);
f_udg = reshape(f_udg,ng,nch,nd,nc);
end