function [f,f_udg] = flux2d(p,udg,param,time)
%FLUX2D
%    [F,F_UDG] = FLUX2D(P,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    10-Sep-2023 21:00:56
[ng,nc] = size(udg);
nch = 3;
nd = 2;
one = ones(ng,1);
param1 = param{1};
param2 = param{2};
param3 = param{3};
u1 = udg(:,1);
u4 = udg(:,4);
u6 = udg(:,6);
u7 = udg(:,7);
u9 = udg(:,9);
x1 = p(:,1);
zero = zeros(ng,1);
t2 = one.*x1;
t3 = u6.^2;
t4 = u9.^2;
t5 = 1.0./param1;
t6 = 1.0./param2;
t7 = 1.0./param3;
t8 = t3+t4;
t9 = sqrt(t8);
t10 = 1.0./t9;
t11 = param3.*t9;
t12 = t11.^(1.1e+1./5.0e+1);
t13 = 1.0./t11.^(1.3e+1./5.0e+1);
t15 = 1.0./t11.^(6.3e+1./5.0e+1);
t14 = t13.^3;
t16 = t6.*t13.*u1.*2.3987;
f = [-x1.*(t16.*u6-t5.*t6.*t7.*t12.*u4.*4.3628e-3);zero;u6.*x1;-x1.*(t16.*u9-t5.*t6.*t7.*t12.*u7.*4.3628e-3);zero;u9.*x1];
if nargout > 1
    t18 = param3.*t6.*t10.*t15.*u1.*u6.*u9.*6.23662e-1;
    t19 = t5.*t6.*t7.*t12.*x1.*4.3628e-3;
    t17 = -t16;
    mt1 = [t6.*t13.*u6.*x1.*(-2.3987);zero;zero;t6.*t13.*u9.*x1.*(-2.3987);zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;t19;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;x1.*(t17+param3.*t3.*t6.*t10.*t15.*u1.*6.23662e-1+t5.*t6.*t10.*t14.*u4.*u6.*9.59816e-4);zero;t2;x1.*(t18+t5.*t6.*t10.*t14.*u6.*u7.*9.59816e-4);zero;zero;zero;zero;zero;t19;zero;zero;zero;zero;zero;zero;zero;zero];
    mt2 = [x1.*(t18+t5.*t6.*t10.*t14.*u4.*u9.*9.59816e-4);zero;zero;x1.*(t17+param3.*t4.*t6.*t10.*t15.*u1.*6.23662e-1+t5.*t6.*t10.*t14.*u7.*u9.*9.59816e-4);zero;t2];
    f_udg = [mt1;mt2];
end
f = reshape(f,ng,nch,nd);
f_udg = reshape(f_udg,ng,nch,nd,nc);
