function [f,f_udg] = flux2d(p,udg,param,time)
%FLUX2D
%    [F,F_UDG] = FLUX2D(P,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    25-Feb-2024 11:27:19
[ng,nc] = size(udg);
nch = 3;
nd = 2;
one = ones(ng,1);
param1 = param{1};
param2 = param{2};
param3 = param{3};
u1 = udg(:,1);
u4 = udg(:,4);
u6 = udg(:,6);
u7 = udg(:,7);
u9 = udg(:,9);
x1 = p(:,1);
zero = zeros(ng,1);
t2 = 1.0./param2;
t3 = u6.^2;
t4 = u9.^2;
t5 = t3+t4;
t6 = sqrt(t5);
t7 = param3.*t6;
t8 = 1.0./t7.^(1.3e1./5.0e1);
t9 = 1.0./param1;
t10 = 1.0./param3;
t11 = t7.^(1.1e1./5.0e1);
f = [-x1.*(t2.*t8.*u1.*u6.*2.3987-t2.*t9.*t10.*t11.*u4.*4.3628e-3);zero;u6.*x1;-x1.*(t2.*t8.*u1.*u9.*2.3987-t2.*t9.*t10.*t11.*u7.*4.3628e-3);zero;u9.*x1];
if nargout > 1
    t12 = 1.0./sqrt(t5);
    t13 = 1.0./t7.^(3.9e1./5.0e1);
    t14 = 1.0./t7.^(6.3e1./5.0e1);
    t15 = t2.*t9.*t10.*t11.*x1.*4.3628e-3;
    t16 = param3.*t2.*t12.*t14.*u1.*u6.*u9.*6.23662e-1;
    t17 = one.*x1;
    f_udg = [t2.*t8.*u6.*x1.*(-2.3987);zero;zero;t2.*t8.*u9.*x1.*(-2.3987);zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;t15;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;x1.*(t2.*t8.*u1.*(-2.3987)+param3.*t2.*t3.*t12.*t14.*u1.*6.23662e-1+t2.*t9.*t12.*t13.*u4.*u6.*9.59816e-4);zero;t17;x1.*(t16+t2.*t9.*t12.*t13.*u6.*u7.*9.59816e-4);zero;zero;zero;zero;zero;t15;zero;zero;zero;zero;zero;zero;zero;zero;x1.*(t16+t2.*t9.*t12.*t13.*u4.*u9.*9.59816e-4);zero;zero;x1.*(t2.*t8.*u1.*(-2.3987)+param3.*t2.*t4.*t12.*t14.*u1.*6.23662e-1+t2.*t9.*t12.*t13.*u7.*u9.*9.59816e-4);zero;t17];
end
f = reshape(f,ng,nch,nd);
f_udg = reshape(f_udg,ng,nch,nd,nc);
