function [s,s_udg] = source2d(p,udg,param,time)
%SOURCE2D
%    [S,S_UDG] = SOURCE2D(P,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    25-Feb-2024 11:27:14

[ng,nc] = size(udg);
nch = 3;
nd = 2;
one = ones(ng,1);
param1 = param{1};
param2 = param{2};
param3 = param{3};
param4 = param{4};
param10 = param{10};
u1 = udg(:,1);
u2 = udg(:,2);
u6 = udg(:,6);
u9 = udg(:,9);
x1 = p(:,1);
zero = zeros(ng,1);
t2 = u6.^2;
t3 = u9.^2;
t4 = t2+t3;
t5 = sqrt(t4);
t6 = 1.0./param2;
t7 = param3.*t5;
t8 = 1.0./t7.^(1.3e1./5.0e1);
t9 = param1.*3.4075e2;
t10 = 1.0./param3;
t11 = 1.0./sqrt(t4);
t18 = t10.*t11.*2.73e7;
t12 = exp(-t18);
t13 = 1.0./param3.^3;
t14 = 1.0./t4.^(3.0./2.0);
t15 = t13.*t14.*4.3666e26;
t16 = t15+1.1944e6;
t19 = param1.*t12.*t16;
t17 = t9-t19;
t20 = 1.0./param1.^2;
s = [t5.*t6.*t8.*t17.*u1.*x1.*(-2.3987);t5.*t6.*t8.*t17.*u1.*x1.*(-2.3987);-param4.*param10.*t10.*t20.*x1.*(u1-u2)];
if nargout > 1
    t21 = 1.0./t4.^(5.0./2.0);
    t22 = param1.*t12.*t13.*t21.*u6.*1.30998e27;
    t23 = t22-param1.*t10.*t12.*t14.*t16.*u6.*2.73e7;
    t24 = 1.0./t7.^(6.3e1./5.0e1);
    t25 = param3.*t6.*t17.*t24.*u1.*u6.*x1.*6.23662e-1;
    t26 = t25-t5.*t6.*t8.*t23.*u1.*x1.*2.3987-t6.*t8.*t11.*t17.*u1.*u6.*x1.*2.3987;
    t27 = param1.*t12.*t13.*t21.*u9.*1.30998e27;
    t28 = t27-param1.*t10.*t12.*t14.*t16.*u9.*2.73e7;
    t29 = param3.*t6.*t17.*t24.*u1.*u9.*x1.*6.23662e-1;
    t30 = t29-t5.*t6.*t8.*t28.*u1.*x1.*2.3987-t6.*t8.*t11.*t17.*u1.*u9.*x1.*2.3987;
    s_udg = [t5.*t6.*t8.*t17.*x1.*(-2.3987);t5.*t6.*t8.*t17.*x1.*(-2.3987);-one.*param4.*param10.*t10.*t20.*x1;zero;zero;one.*param4.*param10.*t10.*t20.*x1;zero;zero;zero;zero;zero;zero;zero;zero;zero;t26;t26;zero;zero;zero;zero;zero;zero;zero;t30;t30;zero];
end
s = reshape(s,ng,nch);
s_udg = reshape(s_udg,ng,nch,nc);


