function [s,s_udg] = source2d2(p,udg,odg,param,factor,time)
%SOURCE2D2
%    [S,S_UDG] = SOURCE2D2(P,UDG,ODG,PARAM,FACTOR,TIME)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Feb-2024 09:57:28
[ng,nc] = size(udg);
nch = 2;
nd = 2;
factor1 = factor(:,1);
o1 = odg(:,1);
param1 = param{1};
param2 = param{2};
param3 = param{3};
param4 = param{4};
param10 = param{10};
u1 = udg(:,1);
u4 = udg(:,4);
u6 = udg(:,6);
x1 = p(:,1);
zero = zeros(ng,1);
t2 = u4.^2;
t3 = u6.^2;
t4 = 1.0./factor1;
t5 = 1.0./param1.^2;
t6 = 1.0./param2;
t7 = 1.0./param3;
t10 = param1.*3.4075e+2;
t8 = t7.^3;
t9 = t2+t3;
t11 = sqrt(t9);
t12 = 1.0./t11;
t15 = param3.*t11;
t13 = t12.^3;
t14 = t12.^5;
t16 = 1.0./t15.^(1.3e+1./5.0e+1);
t17 = 1.0./t15.^(6.3e+1./5.0e+1);
t18 = t7.*t12.*2.73e+7;
t19 = -t18;
t21 = t8.*t13.*4.3666e+26;
t20 = exp(t19);
t22 = t21+1.1944e+6;
t23 = param1.*t8.*t14.*t20.*u4.*1.30998e+27;
t24 = param1.*t8.*t14.*t20.*u6.*1.30998e+27;
t25 = param1.*t20.*t22;
t26 = -t25;
t28 = t7.*t13.*t25.*u4.*2.73e+7;
t29 = t7.*t13.*t25.*u6.*2.73e+7;
t27 = t10+t26;
s = [t6.*t11.*t16.*t27.*u1.*x1.*(-2.3987);-param4.*param10.*t5.*t7.*x1.*(u1-t4.*(o1-t6.*t11.*t16.*t27.*u1.*2.3987))];
if nargout > 1
    t30 = -t28;
    t31 = -t29;
    t32 = t23+t30;
    t33 = t24+t31;
    s_udg = [t6.*t11.*t16.*t27.*x1.*(-2.3987);-param4.*param10.*t5.*t7.*x1.*(t4.*t6.*t11.*t16.*t27.*2.3987+1.0);zero;zero;zero;zero;t6.*t11.*t16.*t32.*u1.*x1.*(-2.3987)+param3.*t6.*t17.*t27.*u1.*u4.*x1.*6.23662e-1-t6.*t12.*t16.*t27.*u1.*u4.*x1.*2.3987;-param4.*param10.*t4.*t5.*t7.*x1.*(t6.*t11.*t16.*t32.*u1.*2.3987-param3.*t6.*t17.*t27.*u1.*u4.*6.23662e-1+t6.*t12.*t16.*t27.*u1.*u4.*2.3987);zero;zero;t6.*t11.*t16.*t33.*u1.*x1.*(-2.3987)+param3.*t6.*t17.*t27.*u1.*u6.*x1.*6.23662e-1-t6.*t12.*t16.*t27.*u1.*u6.*x1.*2.3987;-param4.*param10.*t4.*t5.*t7.*x1.*(t6.*t11.*t16.*t33.*u1.*2.3987-param3.*t6.*t17.*t27.*u1.*u6.*6.23662e-1+t6.*t12.*t16.*t27.*u1.*u6.*2.3987)];
end
s = reshape(s,ng,nch);
s_udg = reshape(s_udg,ng,nch,nc);
