function [s,s_udg] = sourceode2d2(p,udg,param,time)
%SOURCEODE2D2
%    [S,S_UDG] = SOURCEODE2D2(P,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    26-Feb-2024 13:49:42
[ng,nc] = size(udg);
nch = 1;
nd = 2;
param1 = param{1};
param2 = param{2};
param3 = param{3};
u1 = udg(:,1);
u4 = udg(:,4);
u6 = udg(:,6);
zero = zeros(ng,1);
t2 = u4.^2;
t3 = u6.^2;
t4 = t2+t3;
t5 = sqrt(t4);
t6 = 1.0./param2;
t7 = param3.*t5;
t8 = 1.0./t7.^(1.3e1./5.0e1);
t9 = param1.*3.4075e2;
t10 = 1.0./param3;
t11 = 1.0./sqrt(t4);
t18 = t10.*t11.*2.73e7;
t12 = exp(-t18);
t13 = 1.0./param3.^3;
t14 = 1.0./t4.^(3.0./2.0);
t15 = t13.*t14.*4.3666e26;
t16 = t15+1.1944e6;
t19 = param1.*t12.*t16;
t17 = t9-t19;
s = t5.*t6.*t8.*t17.*u1.*(-2.3987);
if nargout > 1
    t20 = 1.0./t4.^(5.0./2.0);
    t21 = 1.0./t7.^(6.3e1./5.0e1);
    s_udg = [t5.*t6.*t8.*t17.*(-2.3987);zero;zero;t5.*t6.*t8.*u1.*(param1.*t12.*t13.*t20.*u4.*1.30998e27-param1.*t10.*t12.*t14.*t16.*u4.*2.73e7).*(-2.3987)+param3.*t6.*t17.*t21.*u1.*u4.*6.23662e-1-t6.*t8.*t11.*t17.*u1.*u4.*2.3987;zero;t5.*t6.*t8.*u1.*(param1.*t12.*t13.*t20.*u6.*1.30998e27-param1.*t10.*t12.*t14.*t16.*u6.*2.73e7).*(-2.3987)+param3.*t6.*t17.*t21.*u1.*u6.*6.23662e-1-t6.*t8.*t11.*t17.*u1.*u6.*2.3987];
end
s = reshape(s,ng,nch);
if nargout > 1
s_udg = reshape(s_udg,ng,nch,nc);
end
